[package]
name = "main"
version = "0.0.0"
edition = "2021"
authors = ["Matvey Safronov"]

[lib]
name = "main"
path = "src/lib.rs"
test = true
doctest = false
crate-type = ["cdylib"]

[dependencies]
presentation_layer = {path = "../presentation_layer"}
application_layer = {path = "../application_layer"}
data_access_layer = {path = "../data_access_layer"}
memory_layer = {path = "../memory_layer"}
infrastructure_layer = {path = "../infrastructure_layer"}
errors = {path = "../errors"}

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[features]
unit_test = []