[package]
name = "infrastructure_layer"
version = "0.0.0"
edition = "2021"
authors = ["Matvey Safronov"]

[lib]
name = "infrastructure_layer"
path = "src/lib.rs"
test = true
doctest = false

[dependencies]
errors = {path = "../errors"}

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[features]
unit_test = []