[package]
name = "errors"
version = "0.0.0"
edition = "2021"
authors = ["Matvey Safronov"]

[lib]
name = "errors"
path = "src/lib.rs"
test = true
doctest = false

[dependencies]

[features]
unit_test = []